name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * * #8:00 AM IST 
   # - cron: 00 14 * * * #7:30 PM IST
jobs: 
  run-postman-test:
    #runs-on: ec2-github-runner
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2
      
      - name: Install Node Js and NPM
        uses: actions/setup-node@v3.9.1
        with:
          node-version:  '22'

      - name: newman install globally
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run the postman collection 
        run: |
             newman run 'Inwarranty-Flow Collection.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testdata.csv \
             -r cli,htmlextra \
             --reporter-htmlextra-export ./newman/index.html
    
      - name: Newman report
        if: always()   #ensure the step is executed irrespective of previous step is passed or failed
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: Newman Report
          path: newman/*.html
      - name: Creating git hub page branch 
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/
      - name: Send Email notifications
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ SECRETS.EMAIL_USERNAME }}
          password: ${{ SECRETS.EMAIL_PASSWORD }}   # THIS IS GMAIL APP PASSWORD
          subject: Phoenix In warranty Test Execution Notification
          to: krthiksantosh@gmail.com
          from: ${{ SECRETS.EMAIL_USERNAME }}
          body: |
                Hi, 
                Phoenix In warranty flow tests have been executed. The report has been published in the following URL
                https://karthiksantosh1993.github.io/Phoenix-Inwarranty-Flow-API-Automation-POSTMAN/
                
        
